import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

#Read .CSV data
df = pd.read_csv("data.csv")

#Split regions into 2 main data frame: Less-develop countries and more-develop countries
groupByRegional = df.groupby('Development') 

#Setup less-develop countries data frame
lessDevelop = pd.DataFrame()
lessDevelop = lessDevelop.append(groupByRegional.get_group('LDC'), ignore_index=True) 

#Setup more-develop countries data frame
moreDevelop = pd.DataFrame()
moreDevelop = moreDevelop.append(groupByRegional.get_group('MDC'), ignore_index=True) 

#THE CODE BELOW IS GENERATED BY JAVA

#Get data of every attribute of less-develop countries
lessDevelopGDP = lessDevelop['Output-side real GDP']
lessDevelopAAH = lessDevelop['Average annual hours']
lessDevelopNOPE = lessDevelop['Number of persons engaged']
lessDevelopP = lessDevelop['Productivity']
lessDevelopCS = lessDevelop['CPI score']
lessDevelopLE = lessDevelop['Life Expectancy']
lessDevelopHCI = lessDevelop['Health Care Index']
lessDevelopCR = lessDevelop['Crime Rate']
lessDevelopQOLI = lessDevelop['Quality of Life Index']
lessDevelopHCII = lessDevelop['Human Capital Index']

#Pot graph for less-develop countries
size = 50
color = "green"
plt.scatter(lessDevelopP, lessDevelopGDP, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Output-side real GDP")
plt.savefig("LessDevelop_0_PvsGDP.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopAAH, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Average annual hours")
plt.savefig("LessDevelop_1_PvsAAH.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopNOPE, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Number of persons engaged")
plt.savefig("LessDevelop_2_PvsNOPE.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopCS, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("CPI score")
plt.savefig("LessDevelop_4_PvsCS.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopLE, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Life Expectancy")
plt.savefig("LessDevelop_5_PvsLE.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopHCI, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Health Care Index")
plt.savefig("LessDevelop_6_PvsHCI.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopCR, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Crime Rate")
plt.savefig("LessDevelop_7_PvsCR.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopQOLI, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Quality of Life Index")
plt.savefig("LessDevelop_8_PvsQOLI.PNG")
plt.close()

plt.scatter(lessDevelopP, lessDevelopHCII, s=size, c=color, alpha=0.2)
plt.title('LessDevelop')
plt.xlabel("Productivity")
plt.ylabel("Human Capital Index")
plt.savefig("LessDevelop_9_PvsHCII.PNG")
plt.close()

#Get data of every attribute of more-develop countries
moreDevelopGDP = moreDevelop['Output-side real GDP']
moreDevelopAAH = moreDevelop['Average annual hours']
moreDevelopNOPE = moreDevelop['Number of persons engaged']
moreDevelopP = moreDevelop['Productivity']
moreDevelopCS = moreDevelop['CPI score']
moreDevelopLE = moreDevelop['Life Expectancy']
moreDevelopHCI = moreDevelop['Health Care Index']
moreDevelopCR = moreDevelop['Crime Rate']
moreDevelopQOLI = moreDevelop['Quality of Life Index']
moreDevelopHCII = moreDevelop['Human Capital Index']

#Pot graph for more-develop countries
size = 50
color = "green"
plt.scatter(moreDevelopP, moreDevelopGDP, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Output-side real GDP")
plt.savefig("MoreDevelop_0_PvsGDP.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopAAH, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Average annual hours")
plt.savefig("MoreDevelop_1_PvsAAH.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopNOPE, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Number of persons engaged")
plt.savefig("MoreDevelop_2_PvsNOPE.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopCS, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("CPI score")
plt.savefig("MoreDevelop_4_PvsCS.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopLE, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Life Expectancy")
plt.savefig("MoreDevelop_5_PvsLE.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopHCI, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Health Care Index")
plt.savefig("MoreDevelop_6_PvsHCI.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopCR, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Crime Rate")
plt.savefig("MoreDevelop_7_PvsCR.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopQOLI, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Quality of Life Index")
plt.savefig("MoreDevelop_8_PvsQOLI.PNG")
plt.close()

plt.scatter(moreDevelopP, moreDevelopHCII, s=size, c=color, alpha=0.2)
plt.title('MoreDevelop')
plt.xlabel("Productivity")
plt.ylabel("Human Capital Index")
plt.savefig("MoreDevelop_9_PvsHCII.PNG")
plt.close()

#Calculate the relationship between 2 attributes by Pearson product-moment correlation coefficient
covariance_matrix=np.cov(lessDevelopP, lessDevelopGDP)
corr, _ = pearsonr(lessDevelopP, lessDevelopGDP)
print('Correlation of LessDevelop\'s Productivity and Output-side real GDP per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopAAH)
corr, _ = pearsonr(lessDevelopP, lessDevelopAAH)
print('Correlation of LessDevelop\'s Productivity and Average annual hours per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopNOPE)
corr, _ = pearsonr(lessDevelopP, lessDevelopNOPE)
print('Correlation of LessDevelop\'s Productivity and Number of persons engaged per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopCS)
corr, _ = pearsonr(lessDevelopP, lessDevelopCS)
print('Correlation of LessDevelop\'s Productivity and CPI score per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopLE)
corr, _ = pearsonr(lessDevelopP, lessDevelopLE)
print('Correlation of LessDevelop\'s Productivity and Life Expectancy per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopHCI)
corr, _ = pearsonr(lessDevelopP, lessDevelopHCI)
print('Correlation of LessDevelop\'s Productivity and Health Care Index per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopCR)
corr, _ = pearsonr(lessDevelopP, lessDevelopCR)
print('Correlation of LessDevelop\'s Productivity and Crime Rate per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopQOLI)
corr, _ = pearsonr(lessDevelopP, lessDevelopQOLI)
print('Correlation of LessDevelop\'s Productivity and Quality of Life Index per capita is: %.3f' % corr)

covariance_matrix=np.cov(lessDevelopP, lessDevelopHCII)
corr, _ = pearsonr(lessDevelopP, lessDevelopHCII)
print('Correlation of LessDevelop\'s Productivity and Human Capital Index per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopGDP)
corr, _ = pearsonr(moreDevelopP, moreDevelopGDP)
print('Correlation of MoreDevelop\'s Productivity and Output-side real GDP per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopAAH)
corr, _ = pearsonr(moreDevelopP, moreDevelopAAH)
print('Correlation of MoreDevelop\'s Productivity and Average annual hours per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopNOPE)
corr, _ = pearsonr(moreDevelopP, moreDevelopNOPE)
print('Correlation of MoreDevelop\'s Productivity and Number of persons engaged per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopCS)
corr, _ = pearsonr(moreDevelopP, moreDevelopCS)
print('Correlation of MoreDevelop\'s Productivity and CPI score per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopLE)
corr, _ = pearsonr(moreDevelopP, moreDevelopLE)
print('Correlation of MoreDevelop\'s Productivity and Life Expectancy per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopHCI)
corr, _ = pearsonr(moreDevelopP, moreDevelopHCI)
print('Correlation of MoreDevelop\'s Productivity and Health Care Index per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopCR)
corr, _ = pearsonr(moreDevelopP, moreDevelopCR)
print('Correlation of MoreDevelop\'s Productivity and Crime Rate per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopQOLI)
corr, _ = pearsonr(moreDevelopP, moreDevelopQOLI)
print('Correlation of MoreDevelop\'s Productivity and Quality of Life Index per capita is: %.3f' % corr)

covariance_matrix=np.cov(moreDevelopP, moreDevelopHCII)
corr, _ = pearsonr(moreDevelopP, moreDevelopHCII)
print('Correlation of MoreDevelop\'s Productivity and Human Capital Index per capita is: %.3f' % corr)
